### ISSUE TITLE
com.apple.dnssd.AppleDNSSDException: DNS-SD Error -65563: SERVICENOTRUNNING

### ISSUE THREAD

**Issue by gurtajs4** [andriydruk/RxDNSSD#12]
Hi,

First of all, I would like to thank you for creating such a nice library for the community to workaround most of the bonjour problems. This is really helpful for applications.

Coming back to the scenario, which I faced and would like to highlight is in your Application AndroidManifest, you haven't specified INTERNET permission and it is instead present in the Library manifest. 
For example look [here](http://stackoverflow.com/questions/30961300/using-apple-mdns-service-in-android).

I think this is real scenario where people try to use this project to check the feasibility and later just integrate the library with their code. You should also highlight adding INTERNET permission  AndroidManifest of application

If also you can reply to the stackoverflow thread

Regards,
Gurtaj

**Comment by andriydruk** [comment]
Hi Gurtaj,

I hope people have already migrated to Gradle and don't build Android projects with Ant. That's why INTERNET permission should be automatically merged into your application manifest from my library (in Android Studio 2.2 was introduced new Merged Manifest tab for AndroidManifest.xml files, take a look)
