### ISSUE TITLE
TxtRecord changed can not trigger BonjourSerivce information update

### ISSUE THREAD

**Issue by NeoLSN** [andriydruk/RxDNSSD#3]
Is there any way to refresh the BonjourService's information when the device has changed txtRecord itself? Can it become automatically in this library?

You can just ignore this problem if this is because Apple's mDnsResponder doesn't support.
I am OK with that.

Right now, my work-around is unsubscribe then resubscribe again.

**Comment by NeoLSN** [comment]
Thank your great job.

**Comment by crachou** [comment]
Hiya,
Using the Rx2 classes I am not notified of changes when the TXT Record changes.
It is related to https://github.com/andriydruk/RxDNSSD/issues/24?

**Comment by andriydruk** [comment]
@crachou yes, autoresolve was switched off by default because it leads to OutOfMemoryException when developers create alot of searches 
I suppose we should create additional method `autoresolve()` alongside with `resolve()`
But keep in mind that every `autoresolve()` will create own thread, that's why you should use it for one or few services simultaneously

**Comment by crachou** [comment]
@andriydruk Thanks for opening it back. 
That's because the query stays opened to monitor changes, right?
If I get it right, if we monitor only one service, and dispose of the observable properly when not used, we shouldn't have any OOM Exception?

**Comment by andriydruk** [comment]
@crachou yes, use new API `queryTXTRecord` for one or few services and OOM wouldn't happen

**Comment by andriydruk** [comment]
I've just published a new version with continuously querying IP addresses or TXT records
https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.10
