### ISSUE TITLE
Is there any timeout operation when browse()?

### ISSUE THREAD

**Issue by smallzhan** [andriydruk/RxDNSSD#7]
I did my bonjour search with 

    rxDnssd.browse("_easylink._tcp.", "local.")
                .takeUntil(Observable.timer(5, TimeUnit.SECONDS))
                .compose(rxDnssd.resolve())
                .compose(rxDnssd.queryRecords())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(...);

And I expect that the `onCompleted' of rxDnssd emitted after 5 seconds, but the result is wired.
If there are nothing found during browse, i.e, no onNext(...) emitted, the `onCompleted' is emitted after 5 seconds, but if there are any 'onNext' emitted during the 5 seconds, There is no `onCompleted'.

**Comment by smallzhan** [comment]
I ’ve tested the code segment in Version 0.7.1,  it works smoothly.

**Comment by andriydruk** [comment]
Hi, I investigated this issue, and I think library works correctly. 
Since version 0.8.0 `rxDnssd.resolve()` became endless operation, that's why queryRecords never sent onComplete (because flatMap usually send onComplete only if all children are completed).

I guess right version should be:
 
`rxDnssd.browse("_easylink._tcp", "local.")
                .compose(rxDnssd.resolve())
                .compose(rxDnssd.queryRecords())
                .takeUntil(Observable.timer(5, TimeUnit.SECONDS))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(...);`

If you will put takeUntil after all flatMaps it would work correctly.
